#!/bin/bash

coqc -R theories/Casteran Ordering theories/Casteran/AccP.v
coqc -R theories/Casteran Ordering theories/Casteran/closure.v
coqc -R theories/Casteran Ordering theories/Casteran/decidable_set.v
coqc -R theories/Casteran Ordering theories/Casteran/more_list.v
coqc -R theories/Casteran Ordering theories/Casteran/list_permut.v
coqc -R theories/Casteran Ordering theories/Casteran/list_set.v
coqc -R theories/Casteran Ordering theories/Casteran/term.v
coqc -R theories/Casteran Ordering theories/Casteran/dickson.v
coqc -R theories/Casteran Ordering theories/Casteran/rpo.v

coqc -R theories/Logic/ Systems theories/Logic/definitions.v

coqc -R theories/Maths/ Maths_Facts theories/Maths/naturals.v
coqc -R theories/Maths/ Maths_Facts theories/Maths/lists.v
coqc -R theories/Maths/ Maths_Facts theories/Maths/ordinals.v

coqc -R theories/Logic/ Systems theories/Logic/fol.v
coqc -R theories/Logic/ Systems theories/Logic/PA_omega.v
coqc -R theories/Logic/ Systems theories/Logic/proof_trees.v
coqc -R theories/Logic/ Systems theories/Logic/substitute.v
coqc -R theories/Logic/ Systems theories/Logic/inverse_neg.v
coqc -R theories/Logic/ Systems theories/Logic/inverse_dem_1.v
coqc -R theories/Logic/ Systems theories/Logic/inverse_dem_2.v
coqc -R theories/Logic/ Systems theories/Logic/inverse_omega.v
coqc -R theories/Logic/ Systems theories/Logic/inverse_quantif.v
coqc -R theories/Logic/ Systems theories/Logic/formula_sub.v
coqc -R theories/Logic/ Systems theories/Logic/Peano.v
coqc -R theories/Logic/ Systems theories/Logic/cut_elim.v

coqc -R theories/ Main theories/gentzen.v
